version: '3'
services:
  web:
    image: gradio
    ports:
      - "7860:7860"
    networks:
      - poc
  api:
    image: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - poc
networks:
  poc:
    driver: bridge