---
name: build and deploy to Azure App Service
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Add .env file
        run: |
          echo "${{ secrets.ENV }}" > mps_audio_fast_api/.env
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/*.dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Build and tag API Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/mps_audio_api:latest -f mps_audio_fast_api/Dockerfile mps_audio_fast_api
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mps_audio_api:latest
      - name: Build and tag Web Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/mps_audio_gradio_web:latest -f mps_audio_gradio/Dockerfile mps_audio_gradio
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mps_audio_gradio_web:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Restart Azure App Service
        run: |
          az webapp restart --resource-group skillmatrix-dev --name gender-identification-app
